### PR TITLE
use Octokit client to download buildx

### LINKED ISSUE #190: Cannot find buildx v0.9.1 release
### Behaviour
Running this action is returning the next message: "Cannot find buildx v0.9.1 release"

This is the step:
```
name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1
        with:
          version: v0.9.1
```

And this is what RUN returns:
```
 with:
    version: v0.9.1
    driver: docker-container
    buildkitd-flags: --allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host
    install: false
    use: true
```

I've been using this version since a few weeks.
Then all of the sudden this error shows up.

Does anyone knows what's going on?
Thanks in advance

### PR DESCRIPTION
**Pull request by crazy-max**
fixes #190

### CODE REVIEW

**Review by tonistiigi — APPROVED** [review]

**Comment by rmg** [comment]
Using `@actions/github` for this will break GH enterprise usage because it would try to download the release from the GH enterprise server it is running on instead of github.com

**Comment by crazy-max** [comment]
@rmg So needs to enforce server url in ocotkit?

**Comment by crazy-max** [comment]
@rmg You mean https://github.com/actions/toolkit/tree/main/packages/github#usage?:

> Returns an authenticated Octokit client that follows the machine [proxy settings](https://help.github.com/en/actions/hosting-your-own-runners/using-a-proxy-server-with-self-hosted-runners) and correctly sets GHES base urls. See https://octokit.github.io/rest.js for the API.

**Comment by rmg** [comment]
Having it as an input is good, but making the default a little smarter would be good, eg: from [`actions/setup-go:action.yml`](https://github.com/actions/setup-go/blob/21459d0b7b1d63741429b748885bf5a4974593b4/action.yml#L12-L14):
```yaml
  token:
    description: Used to pull node distributions from go-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
```

**Comment by rmg** [comment]
`actions/github` creates the client using [`process.env['GITHUB_API_URL']`](https://github.com/actions/toolkit/blob/1589a5c066fbe34ed1c828e9b81b9f206f9a3a40/packages/github/src/internal/utils.ts#L23-L25) which will be different on GHES.

**Comment by tonistiigi** [comment]
@rmg Is there a place where we can hardcode it to `api.github.com` on initialization?

**Comment by crazy-max** [comment]
I think with:

```ts
    const octokit = DefaultOctokit({
      baseUrl: config.GITHUB_API_URL,
    });
```

**Comment by crazy-max** [comment]
@rmg Ah yes just found https://github.com/actions/toolkit/pull/449

**Comment by rmg** [comment]
FWIW it took GitHub a few tries to get this right for their own actions: https://github.com/actions/setup-python/pulls?q=is%3Apr+token+is%3Aclosed

**Pull request merged**
