### PR TITLE
First release

### PR DESCRIPTION
**Pull request by crazy-max**
Ref. docker/build-push-action#87

v1 for our **setup-buildx-action** is ready.

When the repo is made public:

* [x] Uncomment [this job](https://github.com/docker/setup-buildx-action/blob/6a7c1dc2ba44f768e571cdd730d7b8306eeeaa09/.github/workflows/ci.yml#L124-L156) (need [setup-qemu-action](https://github.com/docker/setup-qemu-action) made public too)
* [ ] [Enable Codecov for the repo?](https://codecov.io/gh/docker/setup-buildx-action).
  * If so, [add the `CODECOV_TOKEN` secret](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets-for-a-repository) on the repo to be able to push coverage reports through our [test workflow](https://github.com/docker/setup-buildx-action/blob/master/.github/workflows/test.yml#L27-L33).
  * Add Codecov badge to README: `[Codecov](https://codecov.io/gh/docker/setup-buildx-action)`
* [ ] Publish the action on the marketplace
* [x] Remove [`setup-buildx` folder](https://github.com/docker/build-push-action/tree/v2-working-branch) from build-push action `v2-working-branch` and update workflows
* [x] @justincormack Change repo description to `GitHub Action to set up Docker Buildx` instead?

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

**Comment by crazy-max** [comment]
@justincormack Ready to [publish v1.0.0](https://github.com/docker/setup-buildx-action/releases/new) on the marketplace.

**Comment by tonistiigi** [comment]
I'm a bit cautious on declaring 1.0 right away when we don't have much user feedback yet. Is there any reason this has to be done now (eg. people can't properly use it otherwise) or is this common in github actions to just declare them 1.0 from start?

**Comment by crazy-max** [comment]
@tonistiigi Sure we can release under 0.1.0 that looks good to me. It's only to be concise with [their workflow](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md) (`@v1` ~ `@v1.x.x`).

**Comment by tonistiigi** [comment]
We have a Docker `20.x` release coming up, as well as BuildKit `v0.8`. I suggest we target getting the actions to `v1.0` in a similar timeline. Atm I'm fine with `v0.9.0` as well as setup-buildx and setup-qemu look quite close to completion to me.

**Comment by crazy-max** [comment]
@tonistiigi LGTM yes!

**Pull request merged**
