### PR TITLE
Disable validation for dependabot

### PR DESCRIPTION
**Pull request by crazy-max**
Ref. https://github.com/docker/setup-buildx-action/runs/1161567962?check_suite_focus=true#step:3:160
Dependabot can't update `index.js` by itself. I remove this validation for now.
Or maybe we could skip this job if triggered by Dependabot?

Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>

### CODE REVIEW

**Comment by tonistiigi** [comment]
I'm not sure why we would ever want the repo to be in an inconsistent state. If `index.js` is not updated people will get the wrong version so it is even worse than having an older dependency in package.json.

**Comment by tonistiigi** [comment]
If dependabot can't actually update dependencies correctly then isn't the correct workflow to let it open a PR and if it fails validation then fix it manually before merging. (Could be automated of course but don't think all this is worth it).

**Comment by crazy-max** [comment]
@tonistiigi 

> If dependabot can't actually update dependencies correctly then isn't the correct workflow to let it open a PR and if it fails validation then fix it manually before merging. (Could be automated of course but don't think all this is worth it).

Auto merging to a Dependabot PR can break the underlying workflow used by GitHub for Dependabot unfortunately.

I've updated this PR to only disable the validate target if the vent is triggered by Dependabot for now.

**Comment by crazy-max** [comment]
@tonistiigi I close this PR. When there are new updates to Dependabot we will update the content generated in case of an error directly on the branch created by Dependabot.

**Pull request closed without merging**
